### ISSUE TITLE
Send to multiple AWTRIX displays

### ISSUE THREAD

**Issue by ChrisKoh83** [stanoba/victron-awtrix#1]
Hi,

first your flow is awesome!

Is where a easy way to send the values to multiple Displays?

I doubled the flow and it works but it dosen´t feel right.

Greetings
Christian

**Comment by stanoba** [comment]
Hi, there is also much simpler way... just set the same MQTT topic for all LED matrix displays. :)

**Comment by ChrisKoh83** [comment]
Yes what would be a way :D
but I show different content on the displays.

I think about it and if I have an solution I send you an PR :)

**Comment by stanoba** [comment]
You can also add another `mqtt out` in parallel and change topic for another display.
